CC=g++
SRC=./src/a.cpp
BIN=./bin/a.out
CFLAGS=-std=c++11
LIBS=\
	-lboost_system\
	-lboost_serialization
$(BIN): $(SRC)
	$(CC) $(CFLAGS) $(SRC) $(LIBS) -o $(BIN)
.phony:\
	run\
	clean
run:
	$(BIN)
clean:
	rm $(BIN)
# libboost_atomic.so
# libboost_atomic.so.1
# libboost_atomic.so.1.70
# libboost_atomic.so.1.70.0
# libboost_chrono.so
# libboost_chrono.so.1
# libboost_chrono.so.1.70
# libboost_chrono.so.1.70.0
# libboost_container.so
# libboost_container.so.1
# libboost_container.so.1.70
# libboost_container.so.1.70.0
# libboost_context.so
# libboost_context.so.1
# libboost_context.so.1.70
# libboost_context.so.1.70.0
# libboost_contract.so
# libboost_contract.so.1
# libboost_contract.so.1.70
# libboost_contract.so.1.70.0
# libboost_coroutine.so
# libboost_coroutine.so.1
# libboost_coroutine.so.1.70
# libboost_coroutine.so.1.70.0
# libboost_date_time.so
# libboost_date_time.so.1
# libboost_date_time.so.1.70
# libboost_date_time.so.1.70.0
# libboost_exception.a
# libboost_fiber.so
# libboost_fiber.so.1
# libboost_fiber.so.1.70
# libboost_fiber.so.1.70.0
# libboost_filesystem.so
# libboost_filesystem.so.1
# libboost_filesystem.so.1.70
# libboost_filesystem.so.1.70.0
# libboost_graph.so
# libboost_graph.so.1
# libboost_graph.so.1.70
# libboost_graph.so.1.70.0
# libboost_iostreams.so
# libboost_iostreams.so.1
# libboost_iostreams.so.1.70
# libboost_iostreams.so.1.70.0
# libboost_locale.so
# libboost_locale.so.1
# libboost_locale.so.1.70
# libboost_locale.so.1.70.0
# libboost_math_c99.so
# libboost_math_c99.so.1
# libboost_math_c99.so.1.70
# libboost_math_c99.so.1.70.0
# libboost_math_c99f.so
# libboost_math_c99f.so.1
# libboost_math_c99f.so.1.70
# libboost_math_c99f.so.1.70.0
# libboost_math_c99l.so
# libboost_math_c99l.so.1
# libboost_math_c99l.so.1.70
# libboost_math_c99l.so.1.70.0
# libboost_math_tr1.so
# libboost_math_tr1.so.1
# libboost_math_tr1.so.1.70
# libboost_math_tr1.so.1.70.0
# libboost_math_tr1f.so
# libboost_math_tr1f.so.1
# libboost_math_tr1f.so.1.70
# libboost_math_tr1f.so.1.70.0
# libboost_math_tr1l.so
# libboost_math_tr1l.so.1
# libboost_math_tr1l.so.1.70
# libboost_math_tr1l.so.1.70.0
# libboost_prg_exec_monitor.so
# libboost_prg_exec_monitor.so.1
# libboost_prg_exec_monitor.so.1.70
# libboost_prg_exec_monitor.so.1.70.0
# libboost_program_options.so
# libboost_program_options.so.1
# libboost_program_options.so.1.70
# libboost_program_options.so.1.70.0
# libboost_python27.so
# libboost_python27.so.1
# libboost_python27.so.1.70
# libboost_python27.so.1.70.0
# libboost_python37.so
# libboost_python37.so.1
# libboost_python37.so.1.70
# libboost_python37.so.1.70.0
# libboost_random.so
# libboost_random.so.1
# libboost_random.so.1.70
# libboost_random.so.1.70.0
# libboost_regex.so
# libboost_regex.so.1
# libboost_regex.so.1.70
# libboost_regex.so.1.70.0
# libboost_serialization.so
# libboost_serialization.so.1
# libboost_serialization.so.1.70
# libboost_serialization.so.1.70.0
# libboost_system.so
# libboost_system.so.1
# libboost_system.so.1.70
# libboost_system.so.1.70.0
# libboost_test_exec_monitor.a
# libboost_thread.so
# libboost_thread.so.1
# libboost_thread.so.1.70
# libboost_thread.so.1.70.0
# libboost_timer.so
# libboost_timer.so.1
# libboost_timer.so.1.70
# libboost_timer.so.1.70.0
# libboost_type_erasure.so
# libboost_type_erasure.so.1
# libboost_type_erasure.so.1.70
# libboost_type_erasure.so.1.70.0
# libboost_unit_test_framework.so
# libboost_unit_test_framework.so.1
# libboost_unit_test_framework.so.1.70
# libboost_unit_test_framework.so.1.70.0
# libboost_wave.so
# libboost_wave.so.1
# libboost_wave.so.1.70
# libboost_wave.so.1.70.0
# libboost_wserialization.so
# libboost_wserialization.so.1
# libboost_wserialization.so.1.70
# libboost_wserialization.so.1.70.0
